services:
  pile:
    build:
      context: .
    privileged: true
    cap_add:
      - SYS_PTRACE
    environment:
      - PILE_WORKSPACES_DIR=/users/pile
      - PILE_WORKSPACE
    volumes:
      - .:/pile
      - ${PILE_WORKSPACES_DIR}:/users/pile
